apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deploy
  name: backend-deploy
  namespace: tier3-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: backend-deploy
    spec:
      containers:
      - image: shreyas02/nodejs-backend
        name: nodejs-backend
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST 
          value: "pg-service"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: pg-db-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-db-secret
              key: POSTGRES_PASSWORD
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: pg-db-secret
              key: POSTGRES_DB
        - name: NODE_ENV
          value: "production"
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
        # resources: {
        #   limits: {
        #     cpu: "500m",
        #     memory: "256Mi"
        #   },
        #   requests: {
        #     cpu: "250m",
        #     memory: "128Mi"
        #   }
        # }

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: tier3-apps
spec:
  selector:
    app: backend-deploy
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP